/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CorporateFurnitureRouteImport } from './routes/corporate-furniture'
import { Route as HomeFurnitureRouteImport } from './routes/home-furniture'
import { Route as HotelFurnitureRouteImport } from './routes/hotel-furniture'
import { Route as OfficeFurnitureRouteImport } from './routes/office-furniture'
import { Route as ProjectsRouteImport } from './routes/projects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateFurnitureRoute = CorporateFurnitureRouteImport.update({
  id: '/corporate-furniture',
  path: '/corporate-furniture',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeFurnitureRoute = HomeFurnitureRouteImport.update({
  id: '/home-furniture',
  path: '/home-furniture',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelFurnitureRoute = HotelFurnitureRouteImport.update({
  id: '/hotel-furniture',
  path: '/hotel-furniture',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeFurnitureRoute = OfficeFurnitureRouteImport.update({
  id: '/office-furniture',
  path: '/office-furniture',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corporate-furniture': typeof CorporateFurnitureRoute
  '/home-furniture': typeof HomeFurnitureRoute
  '/hotel-furniture': typeof HotelFurnitureRoute
  '/office-furniture': typeof OfficeFurnitureRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corporate-furniture': typeof CorporateFurnitureRoute
  '/home-furniture': typeof HomeFurnitureRoute
  '/hotel-furniture': typeof HotelFurnitureRoute
  '/office-furniture': typeof OfficeFurnitureRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corporate-furniture': typeof CorporateFurnitureRoute
  '/home-furniture': typeof HomeFurnitureRoute
  '/hotel-furniture': typeof HotelFurnitureRoute
  '/office-furniture': typeof OfficeFurnitureRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corporate-furniture'
    | '/home-furniture'
    | '/hotel-furniture'
    | '/office-furniture'
    | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corporate-furniture'
    | '/home-furniture'
    | '/hotel-furniture'
    | '/office-furniture'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/corporate-furniture'
    | '/home-furniture'
    | '/hotel-furniture'
    | '/office-furniture'
    | '/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorporateFurnitureRoute: typeof CorporateFurnitureRoute
  HomeFurnitureRoute: typeof HomeFurnitureRoute
  HotelFurnitureRoute: typeof HotelFurnitureRoute
  OfficeFurnitureRoute: typeof OfficeFurnitureRoute
  ProjectsRoute: typeof ProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-furniture': {
      id: '/corporate-furniture'
      path: '/corporate-furniture'
      fullPath: '/corporate-furniture'
      preLoaderRoute: typeof CorporateFurnitureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-furniture': {
      id: '/home-furniture'
      path: '/home-furniture'
      fullPath: '/home-furniture'
      preLoaderRoute: typeof HomeFurnitureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-furniture': {
      id: '/hotel-furniture'
      path: '/hotel-furniture'
      fullPath: '/hotel-furniture'
      preLoaderRoute: typeof HotelFurnitureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-furniture': {
      id: '/office-furniture'
      path: '/office-furniture'
      fullPath: '/office-furniture'
      preLoaderRoute: typeof OfficeFurnitureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorporateFurnitureRoute: CorporateFurnitureRoute,
  HomeFurnitureRoute: HomeFurnitureRoute,
  HotelFurnitureRoute: HotelFurnitureRoute,
  OfficeFurnitureRoute: OfficeFurnitureRoute,
  ProjectsRoute: ProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
