/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeFurnitureRouteImport } from './routes/home-furniture'
import { Route as HotelFurnitureRouteImport } from './routes/hotel-furniture'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeFurnitureRoute = HomeFurnitureRouteImport.update({
  id: '/home-furniture',
  path: '/home-furniture',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelFurnitureRoute = HotelFurnitureRouteImport.update({
  id: '/hotel-furniture',
  path: '/hotel-furniture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home-furniture': typeof HomeFurnitureRoute
  '/hotel-furniture': typeof HotelFurnitureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home-furniture': typeof HomeFurnitureRoute
  '/hotel-furniture': typeof HotelFurnitureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home-furniture': typeof HomeFurnitureRoute
  '/hotel-furniture': typeof HotelFurnitureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home-furniture' | '/hotel-furniture'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home-furniture' | '/hotel-furniture'
  id: '__root__' | '/' | '/home-furniture' | '/hotel-furniture'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeFurnitureRoute: typeof HomeFurnitureRoute
  HotelFurnitureRoute: typeof HotelFurnitureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-furniture': {
      id: '/home-furniture'
      path: '/home-furniture'
      fullPath: '/home-furniture'
      preLoaderRoute: typeof HomeFurnitureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-furniture': {
      id: '/hotel-furniture'
      path: '/hotel-furniture'
      fullPath: '/hotel-furniture'
      preLoaderRoute: typeof HotelFurnitureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeFurnitureRoute: HomeFurnitureRoute,
  HotelFurnitureRoute: HotelFurnitureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
